# -*- coding: utf-8 -*-
"""
Content banks for the 6-month IELTS roadmap generator.
All content is hand-authored, grounded in official IELTS test format
(4-part/40-question Listening ~30 min; 3-passage/40-question Reading 60 min;
Writing Task 1 150 words/20 min + Task 2 250 words/40 min; Speaking 3 parts
11-14 min) and Cambridge public band descriptor language (Bands 6-9).
"""

# ---------------------------------------------------------------------------
# 1. GRAMMAR BANK (24 points, B2 -> C1, cycled in 3 pedagogical passes)
# ---------------------------------------------------------------------------
GRAMMAR_BANK = [
    dict(name="Inversion after negative adverbials", level="C1",
         rule="Some negative words can start a sentence: Seldom, Rarely, Never, No sooner...than, Little did..., Under no circumstances. When one of these words comes first, you swap the subject and the auxiliary verb, just like in a question.",
         formula="Negative adverbial + auxiliary + subject + main verb",
         example="Seldom have researchers observed such a rapid shift in {topic_lower}.",
         tip="Only swap the word order when the negative word is at the very start of the sentence. If it stays in its usual place in the middle, do not change the order."),
    dict(name="Inversion in formal conditionals", level="C1",
         rule="In formal writing, you can leave out the word 'if' in some conditional sentences. Instead, you start the clause with Had, Were or Should, and swap the subject and the verb.",
         formula="Had/Were/Should + subject + (not) + past participle / base form, ...",
         example="Had it not been for sustained investment, progress on {topic_lower} would have stalled entirely.",
         tip="Use this pattern only in formal writing. Never use 'if' and the inverted word order together in the same sentence."),
    dict(name="It-cleft sentences", level="C1",
         rule="An it-cleft sentence puts special focus on one part of a sentence — often the real cause, person, or reason.",
         formula="It + is/was + emphasised element + that/who + remainder of clause",
         example="It is precisely the lack of coordinated policy that undermines progress on {topic_lower}.",
         tip="Make sure 'is' or 'was' matches the tense of the rest of the text. Do not use more than one it-cleft in the same paragraph."),
    dict(name="What-cleft (pseudo-cleft) sentences", level="C1",
         rule="A what-cleft sentence puts the main idea at the front. The new or important information usually comes after the verb 'be'.",
         formula="What + clause + is/was + emphasised element",
         example="What concerns experts most about {topic_lower} is the accelerating pace of change.",
         tip="Keep the tense the same in both halves of the sentence. Use this structure only when you really want to emphasise a point."),
    dict(name="Mixed conditional (past cause, present result)", level="C1",
         rule="This links an unreal condition in the past to its unreal result now, in the present. It connects two different time periods in one sentence.",
         formula="If + past perfect, ... would + base verb",
         example="If policymakers had acted sooner on {topic_lower}, the situation would not be so urgent today.",
         tip="Before you write, keep the two time periods clear in your mind: the condition is in the past, and the result is in the present."),
    dict(name="Mixed conditional (present cause, past result)", level="C1",
         rule="This links an unreal situation now with an unreal result in the past. It is less common, but useful when you need to be precise.",
         formula="If + past simple, ... would have + past participle",
         example="If the public were less resistant to change, the reforms on {topic_lower} would have passed years ago.",
         tip="Use this pattern only occasionally, and only when it is really clear that a present situation affected a past result."),
    dict(name="Participle clauses of reason (present participle)", level="C1",
         rule="This is a shorter way to give a reason. You use an -ing verb instead of 'because' or 'since'.",
         formula="[-ing clause], main clause.",
         example="Recognising the risks associated with {topic_lower}, several governments have introduced new safeguards.",
         tip="The person or thing doing the -ing action must be the same as the subject of the main sentence. Otherwise, the meaning becomes unclear."),
    dict(name="Perfect participle clauses (sequence)", level="C1",
         rule="This shows that one action finished before another one started. It puts both actions into one shorter clause.",
         formula="Having + past participle, main clause.",
         example="Having reviewed the evidence on {topic_lower}, the committee revised its original recommendations.",
         tip="Use 'having + past participle' (not just '-ing') whenever the order of events is important."),
    dict(name="Passive with reporting verbs", level="C1",
         rule="This structure makes a claim sound more neutral and less personal. It is common in academic writing and in Task 2 essays.",
         formula="It + is/was + past participle (reporting verb) + that-clause",
         example="It is widely believed that {topic_lower} will remain a defining issue for the next generation.",
         tip="Do not use this structure too many times in one paragraph. Mix it with active sentences so your writing does not sound repetitive."),
    dict(name="Causative passive (have/get something done)", level="B2+",
         rule="This describes asking or paying someone else to do something for you, instead of doing it yourself.",
         formula="have/get + object + past participle",
         example="Many local authorities have had independent studies conducted into {topic_lower}.",
         tip="This is different from a simple passive sentence. The causative shows that the subject arranged the action — not just that it happened to them."),
    dict(name="Mandative subjunctive", level="C1",
         rule="This is used after words like recommend, insist, essential, or vital — words that show a recommendation, a demand, or a necessity.",
         formula="Subject + suggest/recommend/insist + that + subject + base verb (no -s, no tense change)",
         example="Experts recommend that policy on {topic_lower} be reviewed on an annual basis.",
         tip="The verb after 'that' always stays in its base form. It never changes for person or tense: use 'be reviewed', not 'is reviewed' or 'was reviewed'."),
    dict(name="Complex relative clauses with quantifiers", level="C1",
         rule="This adds extra, non-essential information by combining a quantity word (like 'many' or 'most') with 'of which' or 'of whom'.",
         formula="..., [quantifier] of which/whom + clause",
         example="The survey included 1,200 respondents, the majority of whom expressed concern about {topic_lower}.",
         tip="Always put a comma before this structure, because the extra information is not essential. Never use 'that' instead of 'which' or 'whom' here."),
    dict(name="Reduced relative clauses", level="C1",
         rule="This leaves out the relative pronoun (like 'that' or 'which') and the auxiliary verb. It makes the sentence shorter and more academic.",
         formula="Noun + [participle clause] (no relative pronoun)",
         example="Measures aimed at addressing {topic_lower} require sustained political commitment to succeed.",
         tip="You can only shorten a relative clause this way when the pronoun you remove would have been the subject of that clause."),
    dict(name="Concession: despite/in spite of + noun/-ing vs. although + clause", level="B2+",
         rule="This shows a contrast, but the grammar after it depends on the connector you choose. Use a noun or an -ing phrase after 'despite'/'in spite of'. Use a full clause after 'although'/'even though'.",
         formula="Despite/In spite of + noun/-ing, clause. | Although/Even though + clause, clause.",
         example="Despite growing awareness of {topic_lower}, meaningful action has been slow to materialise.",
         tip="Never put a subject + verb clause right after 'despite' or 'in spite of'. This is one of the most common mistakes at B2 level."),
    dict(name="Emphatic do / so...that / such...that", level="B2+",
         rule="The word 'do' can add extra stress to a verb, often to correct or contrast something. 'So...that' and 'such...that' make a description stronger and show its result.",
         formula="Subject + do/does/did + base verb | so + adj/adv + that-clause | such + (a/an) + adj + noun + that-clause",
         example="The evidence on {topic_lower} was so compelling that even sceptical policymakers took notice.",
         tip="Use emphatic 'do' only for real contrast or correction. If you use it too often, it loses its effect."),
    dict(name="Nominalisation for academic register", level="C1",
         rule="This changes verbs or adjectives into nouns — for example, 'reduce' becomes 'reduction'. It creates the formal, impersonal tone used in academic writing.",
         formula="verb/adjective -> noun (reduce -> reduction; aware -> awareness)",
         example="The steady reduction in resources devoted to {topic_lower} has drawn considerable criticism.",
         tip="Do not overuse this. A paragraph full of abstract nouns becomes hard to read, so balance it with clearer, simpler sentences too."),
    dict(name="Hedging language for academic caution", level="C1",
         rule="This makes a claim sound less certain and more careful, so you do not overstate your argument.",
         formula="It + modal (may/might/could) + be + that... | [adverb] + [modal verb]",
         example="It could plausibly be argued that {topic_lower} will require a fundamentally different policy response.",
         tip="Avoid strong words like 'always', 'never', or 'proves' unless you are completely sure your evidence supports them."),
    dict(name="Ellipsis and substitution for cohesion", level="C1",
         rule="This leaves out or replaces a word that was already used earlier in the sentence. It avoids repeating yourself and helps your writing flow better.",
         formula="..., and so + auxiliary + subject | auxiliary + not (omitting the repeated verb phrase)",
         example="Older generations remain cautious about {topic_lower}, and so, increasingly, do younger ones.",
         tip="Only leave out a word when the reader can easily guess it from context. If it is not clear, the sentence becomes confusing instead of smoother."),
    dict(name="Proportional comparatives (the...the...)", level="C1",
         rule="This shows a direct link between two things that change together — when one increases or decreases, so does the other.",
         formula="The + comparative + clause, the + comparative + clause",
         example="The more attention {topic_lower} receives in public debate, the greater the pressure on lawmakers to respond.",
         tip="Keep both halves of the sentence grammatically the same. If they do not match, the sentence sounds wrong."),
    dict(name="Fronting for cohesion and emphasis", level="C1",
         rule="This moves a word or phrase to the start of a sentence. It usually connects back to the previous sentence or highlights an important idea.",
         formula="[Fronted adverbial/object], subject + verb...",
         example="Central to any serious discussion of {topic_lower} is the question of who ultimately bears responsibility.",
         tip="Use this mainly to connect your sentences clearly, not just to make your writing sound more varied."),
    dict(name="Modal perfect for past speculation", level="B2+",
         rule="This shows how certain or uncertain you are about something in the past. You use a modal verb followed by 'have + past participle'.",
         formula="Subject + must/might/could/should + have + past participle",
         example="The delay in addressing {topic_lower} must have resulted from competing political priorities.",
         tip="Choose the modal verb carefully. 'Must have' shows you are almost sure. 'Might have' or 'could have' shows it is just possible."),
    dict(name="Appositive noun phrases", level="C1",
         rule="This adds a noun phrase right after another noun, to explain or add detail about it, without using a separate relative clause.",
         formula="Noun, [appositive noun phrase], verb...",
         example="Concern over {topic_lower}, once dismissed as a marginal issue, now dominates national policy debates.",
         tip="Put commas around this extra noun phrase, and keep it short so it does not make the sentence too heavy."),
    dict(name="Correlative conjunctions (not only...but also)", level="C1",
         rule="This connects two balanced ideas using a pair of linking words. When 'not only' starts the sentence, it triggers inversion in that clause.",
         formula="Not only + [inverted clause], but + subject + also + verb",
         example="Not only does {topic_lower} affect the economy, but it also reshapes everyday social behaviour.",
         tip="Remember: if 'not only' is at the start of the sentence, you must invert the subject and verb. If it is in the middle, you do not."),
    dict(name="Absolute constructions", level="C1",
         rule="This is a phrase with its own hidden subject, different from the subject of the main sentence. It adds background information without using a conjunction.",
         formula="Noun + participle (present/past), main clause.",
         example="Resources permitting, further research into {topic_lower} could yield significant long-term benefits.",
         tip="This is different from a participle clause: here, the noun is not the same as the subject of the main sentence."),
]

# ---------------------------------------------------------------------------
# 2. TOPIC BANK (26 topics, one per week, thematically progressive)
# ---------------------------------------------------------------------------
TOPICS = [
    "Environment & Climate Change",
    "Technology & Artificial Intelligence",
    "Education & Learning",
    "Health & Wellbeing",
    "Urban Development & Housing",
    "Globalisation & Trade",
    "Work, Careers & the Gig Economy",
    "Media, Advertising & Social Media",
    "Crime, Law & Punishment",
    "Government, Policy & Public Spending",
    "Family, Society & Demographics",
    "Culture, Tradition & Identity",
    "Science, Space & Innovation",
    "Transport & Infrastructure",
    "Tourism & Travel",
    "Arts, Museums & Heritage",
    "Sport & Recreation",
    "Food, Agriculture & Sustainability",
    "Energy & Natural Resources",
    "Population Growth & Ageing Societies",
    "Privacy, Surveillance & Data",
    "Wildlife & Conservation",
    "Inequality & Poverty",
    "Language & the Globalisation of English",
    "The Future of Work & Automation",
    "Exam Mindset, Wellbeing & Peak Performance",
]

# ---------------------------------------------------------------------------
# 3. VOCABULARY / COLLOCATION BANK (8 per topic, C1 academic collocations)
# ---------------------------------------------------------------------------
VOCAB_BANK = {
"Environment & Climate Change": [
    ("reduce/offset a carbon footprint", "Many corporations now publish annual reports detailing efforts to offset their carbon footprint."),
    ("renewable energy sources", "Investment in renewable energy sources has doubled over the past decade."),
    ("greenhouse gas emissions", "Greenhouse gas emissions from heavy industry remain the single largest contributor to global warming."),
    ("environmental degradation", "Unchecked deforestation has accelerated environmental degradation across the region."),
    ("sustainable development", "Sustainable development requires balancing economic growth with ecological preservation."),
    ("biodiversity loss", "Biodiversity loss driven by habitat destruction poses a long-term threat to food security."),
    ("ecological footprint", "Urban planners are increasingly designing cities to shrink residents' ecological footprint."),
    ("climate resilience", "Coastal cities are investing heavily in climate resilience infrastructure to withstand rising sea levels."),
],
"Technology & Artificial Intelligence": [
    ("artificial intelligence", "Artificial intelligence is transforming diagnostic accuracy in modern healthcare."),
    ("cutting-edge technology", "Start-ups are racing to commercialise cutting-edge technology before larger competitors catch up."),
    ("digital transformation", "The pandemic accelerated digital transformation across virtually every industry."),
    ("data privacy concerns", "Data privacy concerns have prompted stricter regulation of technology companies."),
    ("automation of routine tasks", "The automation of routine tasks has freed employees to focus on higher-value work."),
    ("technological advancement", "Rapid technological advancement has outpaced the regulatory frameworks meant to govern it."),
    ("algorithmic bias", "Researchers have raised concerns about algorithmic bias in automated hiring systems."),
    ("the digital divide", "The digital divide between urban and rural communities widened during remote learning."),
],
"Education & Learning": [
    ("academic achievement", "Parental involvement is strongly correlated with academic achievement."),
    ("lifelong learning", "Employers increasingly value lifelong learning over a single academic qualification."),
    ("curriculum reform", "Curriculum reform has placed greater emphasis on critical thinking skills."),
    ("rote memorisation", "Critics argue that rote memorisation does little to foster genuine understanding."),
    ("access to higher education", "Access to higher education remains uneven across socioeconomic groups."),
    ("vocational training", "Vocational training offers a practical alternative to traditional university pathways."),
    ("academic rigour", "The new syllabus was praised for maintaining academic rigour while improving accessibility."),
    ("formative assessment", "Formative assessment allows teachers to identify learning gaps before they widen."),
],
"Health & Wellbeing": [
    ("a sedentary lifestyle", "A sedentary lifestyle has been linked to a range of chronic health conditions."),
    ("preventive healthcare", "Investment in preventive healthcare reduces long-term costs to public health systems."),
    ("mental wellbeing", "Employers are increasingly recognising the importance of mental wellbeing to overall productivity."),
    ("a public health campaign", "The public health campaign significantly reduced smoking rates within five years."),
    ("rising life expectancy", "Improvements in sanitation have contributed to rising life expectancy worldwide."),
    ("healthcare disparities", "Healthcare disparities between urban and rural populations remain a pressing policy issue."),
    ("a balanced diet", "Nutritionists consistently emphasise the benefits of a balanced diet over restrictive fad diets."),
    ("chronic illness", "The rising prevalence of chronic illness places sustained pressure on healthcare budgets."),
],
"Urban Development & Housing": [
    ("urban sprawl", "Urban sprawl has placed increasing strain on existing transport infrastructure."),
    ("affordable housing", "The shortage of affordable housing has pushed many young professionals to the city outskirts."),
    ("gentrification", "Gentrification has transformed the neighbourhood's demographic and economic profile."),
    ("public infrastructure", "Ageing public infrastructure requires substantial investment to meet growing demand."),
    ("a housing shortage", "The housing shortage has driven rental prices to record highs in major cities."),
    ("mixed-use development", "Mixed-use development integrates residential, commercial and recreational spaces within a single district."),
    ("urban regeneration", "Urban regeneration projects have revitalised previously neglected industrial areas."),
    ("population density", "High population density places considerable pressure on local amenities and services."),
],
"Globalisation & Trade": [
    ("global supply chains", "Disruptions to global supply chains exposed the fragility of just-in-time manufacturing."),
    ("trade liberalisation", "Trade liberalisation has lowered consumer prices but intensified competition for domestic industries."),
    ("cultural homogenisation", "Critics warn that globalisation risks cultural homogenisation at the expense of local traditions."),
    ("economic interdependence", "Growing economic interdependence has made nations more vulnerable to external shocks."),
    ("multinational corporations", "Multinational corporations wield considerable influence over national economic policy."),
    ("foreign direct investment", "Foreign direct investment has fuelled rapid industrialisation in several emerging economies."),
    ("a competitive advantage", "Access to cheaper labour once gave manufacturing nations a clear competitive advantage."),
    ("protectionist policies", "A resurgence of protectionist policies has slowed the pace of global trade growth."),
],
"Work, Careers & the Gig Economy": [
    ("work-life balance", "Flexible scheduling has become a key factor in employees' work-life balance."),
    ("job security", "The rise of short-term contracts has eroded traditional notions of job security."),
    ("the gig economy", "The gig economy offers flexibility but often lacks the protections of conventional employment."),
    ("professional development", "Companies that invest in professional development report higher staff retention."),
    ("remote working arrangements", "Remote working arrangements have reshaped expectations around office attendance."),
    ("career progression", "Limited career progression remains a leading cause of employee turnover."),
    ("a skill shortage", "A persistent skill shortage in the technology sector has driven up starting salaries."),
    ("burnout and overwork", "Rising rates of burnout and overwork have prompted calls for a four-day working week."),
],
"Media, Advertising & Social Media": [
    ("media literacy", "Media literacy programmes help students critically evaluate online information."),
    ("targeted advertising", "Targeted advertising relies on extensive collection of users' personal data."),
    ("misinformation and disinformation", "Social media platforms face mounting pressure to curb the spread of misinformation and disinformation."),
    ("sensationalist reporting", "Sensationalist reporting can distort public perception of otherwise minor events."),
    ("an echo chamber", "Algorithmic curation tends to reinforce an echo chamber of like-minded opinions."),
    ("consumer behaviour", "Influencer marketing has reshaped consumer behaviour among younger demographics."),
    ("screen time", "Paediatricians recommend limiting children's screen time to protect healthy development."),
    ("public discourse", "Social media has fundamentally altered the tone and pace of public discourse."),
],
"Crime, Law & Punishment": [
    ("a deterrent effect", "Studies dispute whether harsher sentencing has any meaningful deterrent effect."),
    ("rehabilitation programmes", "Rehabilitation programmes aim to reduce reoffending rates among young offenders."),
    ("juvenile delinquency", "Poverty and family instability are frequently cited as contributing factors in juvenile delinquency."),
    ("law enforcement", "Community policing has improved trust between residents and law enforcement."),
    ("a custodial sentence", "Judges increasingly favour community service over a custodial sentence for non-violent offences."),
    ("white-collar crime", "White-collar crime often goes undetected for years due to its complexity."),
    ("crime prevention", "Improved street lighting has proven an unexpectedly effective crime prevention measure."),
    ("a miscarriage of justice", "Advances in forensic science have helped overturn several historic miscarriages of justice."),
],
"Government, Policy & Public Spending": [
    ("public expenditure", "Public expenditure on healthcare has risen steadily as populations age."),
    ("fiscal policy", "Expansionary fiscal policy is often used to stimulate a slowing economy."),
    ("a regulatory framework", "A robust regulatory framework is essential to prevent market abuse."),
    ("budget allocation", "Budget allocation for public transport has lagged behind population growth."),
    ("policy implementation", "Effective policy implementation depends on coordination between national and local government."),
    ("the taxation system", "Reforming the taxation system remains politically contentious."),
    ("the welfare state", "Debate continues over the appropriate scope of the modern welfare state."),
    ("government subsidies", "Government subsidies have made electric vehicles more accessible to average consumers."),
],
"Family, Society & Demographics": [
    ("the nuclear family", "The traditional nuclear family has become less prevalent in many industrialised societies."),
    ("social cohesion", "Community programmes play a vital role in strengthening social cohesion."),
    ("an intergenerational gap", "An intergenerational gap in attitudes towards technology often causes friction within families."),
    ("shifting demographics", "Shifting demographics are placing unprecedented strain on pension systems."),
    ("social mobility", "Access to quality education is widely regarded as key to improving social mobility."),
    ("the extended family", "In many cultures, the extended family continues to play a central caregiving role."),
    ("household composition", "Household composition has diversified considerably over the past two generations."),
    ("a social safety net", "A robust social safety net cushions the impact of economic downturns on vulnerable families."),
],
"Culture, Tradition & Identity": [
    ("cultural heritage", "Preserving cultural heritage requires ongoing investment alongside genuine community engagement."),
    ("cultural assimilation", "Debate persists over the balance between cultural assimilation and the preservation of identity."),
    ("traditional customs", "Younger generations are reinterpreting traditional customs rather than abandoning them outright."),
    ("cultural diversity", "Cultural diversity is increasingly recognised as an asset to innovation and creativity."),
    ("national identity", "Immigration debates frequently intersect with anxieties over national identity."),
    ("intangible heritage", "UNESCO recognises oral storytelling traditions as part of humanity's intangible heritage."),
    ("cultural appropriation", "Cultural appropriation remains a contentious issue within the fashion industry."),
    ("the preservation of language", "The preservation of language is central to safeguarding indigenous cultural identity."),
],
"Science, Space & Innovation": [
    ("a scientific breakthrough", "The scientific breakthrough paved the way for a new generation of vaccines."),
    ("space exploration", "Private companies have dramatically lowered the cost of space exploration."),
    ("technological innovation", "Technological innovation has historically been a key driver of economic growth."),
    ("empirical evidence", "Policy decisions should, wherever possible, be grounded in empirical evidence."),
    ("groundbreaking research", "Groundbreaking research into gene editing has raised complex ethical questions."),
    ("interdisciplinary collaboration", "Interdisciplinary collaboration between engineers and biologists produced the prosthetic breakthrough."),
    ("scientific consensus", "There is now overwhelming scientific consensus on the causes of global warming."),
    ("research funding", "Declining research funding threatens to slow the pace of medical innovation."),
],
"Transport & Infrastructure": [
    ("the public transport network", "Expanding the public transport network has reduced private car dependency in the city centre."),
    ("traffic congestion", "Traffic congestion costs commuters an estimated hundred hours annually."),
    ("infrastructure investment", "Long-term infrastructure investment is essential to accommodate population growth."),
    ("carbon-neutral transport", "Several European cities have committed to fully carbon-neutral transport by 2035."),
    ("commuting patterns", "Remote work has permanently altered traditional commuting patterns."),
    ("road safety measures", "Stricter road safety measures have contributed to a steady decline in traffic fatalities."),
    ("transport accessibility", "Improving transport accessibility is critical for residents in remote rural areas."),
    ("high-speed rail", "High-speed rail has significantly reduced domestic air travel in several countries."),
],
"Tourism & Travel": [
    ("mass tourism", "Mass tourism has placed unsustainable pressure on several historic city centres."),
    ("sustainable tourism", "Sustainable tourism initiatives aim to minimise environmental impact while supporting local economies."),
    ("cultural exchange", "Travel fosters cultural exchange that formal education alone cannot replicate."),
    ("tourist infrastructure", "Rapid growth in visitor numbers has outpaced local tourist infrastructure."),
    ("overtourism", "Venice has become a widely cited example of the damaging effects of overtourism."),
    ("economic dependency on tourism", "Small island nations often face heavy economic dependency on tourism revenue."),
    ("heritage site preservation", "Heritage site preservation requires careful management of visitor numbers."),
    ("eco-friendly accommodation", "Demand for eco-friendly accommodation has grown alongside environmental awareness."),
],
"Arts, Museums & Heritage": [
    ("artistic expression", "Public funding for the arts safeguards space for unconventional artistic expression."),
    ("a cultural institution", "The museum, a venerable cultural institution, attracts visitors from around the world."),
    ("the creative industries", "The creative industries now contribute a significant share of national GDP."),
    ("public funding for the arts", "Cuts to public funding for the arts have forced many galleries to rely on private sponsorship."),
    ("artistic merit", "Critics disagreed sharply over the artistic merit of the controversial installation."),
    ("cultural preservation", "Digitisation projects support cultural preservation by archiving fragile historical artefacts."),
    ("the contemporary art scene", "The city's contemporary art scene has flourished thanks to a wave of independent galleries."),
    ("heritage conservation", "Heritage conservation efforts have restored several buildings once slated for demolition."),
],
"Sport & Recreation": [
    ("competitive sport", "Competitive sport teaches resilience alongside physical fitness."),
    ("grassroots participation", "Investment in grassroots participation is essential to developing future sporting talent."),
    ("sedentary habits", "Sedentary habits among children have prompted renewed calls for compulsory physical education."),
    ("sporting achievement", "National pride is often closely tied to sporting achievement on the international stage."),
    ("physical and mental resilience", "Team sports cultivate both physical and mental resilience in young participants."),
    ("recreational facilities", "Local councils have expanded recreational facilities to encourage community fitness."),
    ("the professionalisation of sport", "The professionalisation of sport has brought significant commercial pressures to amateur leagues."),
    ("sports sponsorship", "Sports sponsorship deals have become a major revenue stream for governing bodies."),
],
"Food, Agriculture & Sustainability": [
    ("food security", "Climate volatility poses a growing threat to global food security."),
    ("intensive farming", "Intensive farming practices have been linked to declining soil fertility."),
    ("organic produce", "Demand for organic produce has grown steadily among health-conscious consumers."),
    ("sustainable agriculture", "Sustainable agriculture balances crop yield with long-term environmental health."),
    ("food waste reduction", "Supermarkets have introduced initiatives aimed at food waste reduction."),
    ("genetically modified crops", "Genetically modified crops remain a contentious issue among consumers and regulators alike."),
    ("supply chain traceability", "Supply chain traceability allows consumers to verify the origin of their food."),
    ("dietary habits", "Urbanisation has significantly altered traditional dietary habits."),
],
"Energy & Natural Resources": [
    ("fossil fuel dependency", "Reducing fossil fuel dependency remains central to national climate strategies."),
    ("energy efficiency", "Improved energy efficiency in buildings can cut household bills substantially."),
    ("non-renewable resources", "Continued reliance on non-renewable resources is widely regarded as unsustainable."),
    ("energy security", "Diversifying energy imports has become a priority for national energy security."),
    ("the transition to clean energy", "The transition to clean energy requires substantial upfront infrastructure investment."),
    ("resource depletion", "Resource depletion has intensified geopolitical competition over remaining reserves."),
    ("power generation capacity", "Expanding power generation capacity is essential to meet rising demand."),
    ("energy consumption patterns", "Smart meters have given households greater insight into their energy consumption patterns."),
],
"Population Growth & Ageing Societies": [
    ("an ageing population", "An ageing population places mounting pressure on pension and healthcare systems."),
    ("the population growth rate", "The population growth rate has slowed considerably in most developed economies."),
    ("a demographic shift", "This demographic shift will reshape labour markets over the coming decades."),
    ("the dependency ratio", "A rising dependency ratio means fewer workers must support a growing number of retirees."),
    ("a declining birth rate", "Economic uncertainty has been cited as a factor behind the declining birth rate."),
    ("a workforce shortage", "An ageing population is expected to exacerbate an already tight workforce shortage."),
    ("the retirement age", "Several governments have raised the retirement age in response to demographic pressures."),
    ("urban population growth", "Urban population growth has outstripped the capacity of existing housing stock."),
],
"Privacy, Surveillance & Data": [
    ("data protection legislation", "Data protection legislation has tightened considerably in response to high-profile breaches."),
    ("mass surveillance", "Civil liberties groups have raised concerns over the expansion of mass surveillance."),
    ("personal data collection", "Personal data collection by technology firms has come under increasing regulatory scrutiny."),
    ("cybersecurity threats", "Cybersecurity threats have grown more sophisticated alongside greater digital connectivity."),
    ("informed consent", "Genuine informed consent is difficult to obtain when privacy policies remain deliberately opaque."),
    ("a digital footprint", "Every online transaction contributes to an individual's growing digital footprint."),
    ("a data breach", "The company faced significant reputational damage following the data breach."),
    ("encryption technology", "Encryption technology underpins the security of most modern financial transactions."),
],
"Wildlife & Conservation": [
    ("endangered species", "Poaching remains the primary threat to several critically endangered species."),
    ("habitat destruction", "Habitat destruction driven by agricultural expansion is the leading cause of species decline."),
    ("conservation efforts", "International conservation efforts have helped stabilise several previously dwindling populations."),
    ("a biodiversity hotspot", "Rainforests are widely regarded as the planet's richest biodiversity hotspots."),
    ("wildlife trafficking", "Wildlife trafficking generates billions of dollars annually for organised crime networks."),
    ("protected areas", "Expanding protected areas has proven one of the most effective conservation strategies."),
    ("ecosystem services", "Wetlands provide invaluable ecosystem services, including natural flood defence."),
    ("a captive breeding programme", "A captive breeding programme has helped reintroduce the species into its native habitat."),
],
"Inequality & Poverty": [
    ("income inequality", "Income inequality has widened significantly in several advanced economies over recent decades."),
    ("wealth distribution", "Uneven wealth distribution remains a persistent source of social tension."),
    ("poverty alleviation", "Microfinance schemes have played a modest but meaningful role in poverty alleviation."),
    ("social stratification", "Social stratification continues to shape access to education and healthcare."),
    ("a living wage", "Campaigners argue that the minimum wage still falls short of a genuine living wage."),
    ("marginalised communities", "Marginalised communities are often disproportionately affected by economic downturns."),
    ("upward mobility", "Limited upward mobility has fuelled growing disillusionment among younger generations."),
    ("the wealth gap", "The widening wealth gap has become a defining political issue of the decade."),
],
"Language & the Globalisation of English": [
    ("a lingua franca", "English has become the de facto lingua franca of international business and academia."),
    ("linguistic diversity", "Globalisation has raised concerns about the erosion of linguistic diversity."),
    ("language acquisition", "Immersive environments significantly accelerate second-language acquisition."),
    ("native-like fluency", "Achieving native-like fluency typically requires years of sustained, deliberate practice."),
    ("cross-cultural communication", "Effective cross-cultural communication is increasingly essential in globalised workplaces."),
    ("language endangerment", "Language endangerment accelerates as younger generations shift to dominant regional languages."),
    ("bilingual education", "Research consistently highlights the cognitive benefits of bilingual education."),
    ("code-switching", "Code-switching between languages is a common feature of multilingual communities."),
],
"The Future of Work & Automation": [
    ("workforce automation", "Workforce automation is projected to reshape a third of existing job roles within a decade."),
    ("reskilling initiatives", "Reskilling initiatives are essential to help displaced workers transition into emerging industries."),
    ("AI integration", "AI integration into everyday operations has accelerated across most sectors."),
    ("labour market disruption", "Labour market disruption caused by automation disproportionately affects low-skilled roles."),
    ("future-proof skills", "Educators are under pressure to equip students with genuinely future-proof skills."),
    ("a hybrid working model", "Many organisations have settled on a hybrid working model combining office and remote days."),
    ("job displacement", "Job displacement caused by automation remains a central concern for policymakers."),
    ("human-machine collaboration", "Human-machine collaboration, rather than outright replacement, characterises most current automation."),
],
"Exam Mindset, Wellbeing & Peak Performance": [
    ("exam-related anxiety", "Structured practice under timed conditions can meaningfully reduce exam-related anxiety."),
    ("peak performance", "Athletes and students alike benefit from routines designed to support peak performance."),
    ("self-regulation strategies", "Self-regulation strategies help candidates manage time effectively during high-pressure tasks."),
    ("cognitive fatigue", "Cognitive fatigue tends to set in during the final stretch of a long examination."),
    ("a growth mindset", "Cultivating a growth mindset allows candidates to view setbacks as part of the learning process."),
    ("stress management techniques", "Simple stress management techniques, such as controlled breathing, can improve focus under pressure."),
    ("a consistent practice routine", "A consistent practice routine, sustained over months, outperforms last-minute cramming."),
    ("a test-taking strategy", "A clear test-taking strategy prevents candidates from losing marks to poor time allocation."),
],
}
